import Head from 'next/head'
import { Suspense } from "react"
import { Canvas, useLoader } from "@react-three/fiber"
import { Environment, OrbitControls } from "@react-three/drei"
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader"

const Model = () => {
  const gltf = useLoader(GLTFLoader, "/test2.gltf");


  return (
    <>
      <primitive object={gltf.scene} scale={0.05} />
    </>
  );
};

const OfficeDesk = () => {
  return <Canvas shadows dpr={[1, 2]} camera={{ position: [0, 0, 4], fov: 50 }}>
    <ambientLight intensity={0.7} />
    <spotLight intensity={0.5} angle={0.1} penumbra={1} position={[10, 15, 10]} castShadow />
    <Suspense fallback={null}>
      <Model />
      <Environment preset="city" />
    </Suspense>
    <OrbitControls />
  </Canvas>
}

export default function Home() {
  const handleClick = () => {
    console.log("click!!")
  }
  return (
    <div>
      <Head>
        <title>Three.js Example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="globe relative">
        <OfficeDesk />
        {/* {Array(5).fill(0).map((_, i) => (
          <div key={i}>
            <div className='w-16 h-16 bg-yellow-200 rounded-full absolute opacity-50' onClick={handleClick}></div>
          </div>
        ))} */}
      </div>

    </div>
  )
}